version: '3'
services:
  client:
    build: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    container_name: rfc-scraper-client
    depends_on:
      - server
  server:
    build: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 8000:8000
    container_name: rfc-scraper-server