version: '3.7'
services:
  client:
    build:
      context: ./client
    expose:
      - '3000'
    links:
      - server
    ports:
      - '3000:3000'
    stdin_open: true
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    command: npm run start
  server:
    build:
      context: ./server
    expose:
      - '8000'
    ports:
      - '8000:8000'
    volumes:
      - ./server/src:/app/server/src
    command: npm run dev